### ISSUE TITLE
Idea: Family Tree?

### ISSUE THREAD

**Issue by SgtMustang** [Owlchemist/owls-colonist-bar#1]
Do you think family tree functionality would be within the scope of what you're attempting here? There currently aren't any real supported, working mods that accomplish this (the "Family Tree" mod is not being updated anymore by its author). It would be nice to see a mapping of the family members, colonists and non-colonist wise (i.e., different faction members) for all of your colonists.

Thanks for all the excellent work you do in general. As someone in the IT world, I appreciate your commitment to clean & high-performance code and feel a lot of your work substantially enhances the experience.

**Comment by Owlchemist** [comment]
It's a neat idea I'll give you that, just outside of the scope of a colonist bar.
