### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by LionelColaso** [Owlchemist/owls-colonist-bar#2]
https://gist.github.com/HugsLibRecordKeeper/111b2f6b01a3bdec28d4bfd73de6a686

happens only when i add your mod
 
game loads and map loads and is unplayable  screen moves  ,  menu  , colony bar all disappear 

 mods and configs
[bar.zip](https://github.com/Owlchemist/owls-colonist-bar/files/10491658/bar.zip)

save file
[Avengers.zip](https://github.com/Owlchemist/owls-colonist-bar/files/10491731/Avengers.zip)

**Comment by Owlchemist** [comment]
Thanks, I think I see the problem. Gimme sec

**Comment by Owlchemist** [comment]
I was not able to reproduce the error using your save or my other methods. But I think I could see how it could in theory happen, so consider this a blind fix. I pushed it out now, lemme know if it doesn't work.

**Comment by LionelColaso** [comment]
Nope same issue 
https://gist.github.com/HugsLibRecordKeeper/30c29755664a22466de3bd2f5e7cbbeb

removed rocketman cache and try again
https://gist.github.com/HugsLibRecordKeeper/b86981893fc41baee78e068244a5beb3

![Screenshot_20230125_011617](https://user-images.githubusercontent.com/2488703/214393592-4ba0f252-d24f-4eff-8de5-ccbf8df8f10b.png)

**Comment by LionelColaso** [comment]
u can replicate with this contains everything 

https://ufile.io/c1gbrgdt

**Comment by Owlchemist** [comment]
Alright thanks, I can in fact reproduce it with this save. Looking into it now.

**Comment by Owlchemist** [comment]
v0.7.2 pushed, should fix it.

**Comment by LionelColaso** [comment]
issue fixed now thanks
